### ISSUE TITLE
Storage Container replaced during upgrade under PRC

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-azure#2330]
### Describe what happened

The following example causes a replacement without any changes to the program in the storage:Container resource when upgrading from 5.60.0 to 5.87.0

This reproduces in TF when upgrading from 3.85.0 to 3.117.0 when run with `terraform plan -refresh=false`

```hcl
provider "azurerm" {
  features {}
  version = "3.85.0"
}

resource "azurerm_resource_group" "exampleResourceGroup" {
  name     = "exampleResourceGroup123"
  location = "East US"
}

resource "azurerm_storage_account" "exampleAccount" {
  name                     = "examplestorageaccount123"
  resource_group_name      = azurerm_resource_group.exampleResourceGroup.name
  location                 = azurerm_resource_group.exampleResourceGroup.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  tags = {
    environment = "staging"
  }
}

resource "azurerm_storage_container" "exampleContainer" {
  name                  = "examplecontainer123"
  storage_account_name  = azurerm_storage_account.exampleAccount.name
  container_access_type = "private"
}

```

### Sample program

```yaml
name: azure_2322_2
runtime: yaml
outputs: {}
resources:
  prov:
    type: pulumi:providers:azure
    options:
      version: 5.60.0
    defaultProvider: true

  exampleResourceGroup:
    type: azure:core:ResourceGroup
    properties:
      location: East US

  exampleAccount:
    type: azure:storage:Account
    properties:
      resourceGroupName: ${exampleResourceGroup.name}
      location: ${exampleResourceGroup.location}
      accountTier: Standard
      accountReplicationType: LRS
      tags:
        environment: staging
  exampleContainer:
    type: azure:storage:Container
    properties:
      storageAccountName: ${exampleAccount.name}
      containerAccessType: private

```

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
