### ISSUE TITLE
FunctionApp : how to deploy a Function app as Linux Container ?

### ISSUE THREAD

**Issue by StefH** [pulumi/pulumi-azure#504]
I want to deploy an Azure Function on a Linux App Service plan using a Container deployment.

When doing this manually, I see:
![image](https://user-images.githubusercontent.com/249938/77899096-802a7a00-727c-11ea-9ff8-2fe28624b1b9.png)

However when deployed using Pulumi, I cannot define in the stack that I want a Linux container?
There seems to be a `Kind` in the SDK? (https://github.com/pulumi/pulumi-azure/blob/ffeb2d2020298598f12fd7705bde6cf7ccf3cd36/sdk/dotnet/Appservice/FunctionApp.cs#L418) How to use this when creating an function?

Normally in Azure Pipelines, this can be configured using:
``` yaml
    - task: AzureFunctionApp@1
      condition: and(succeeded(), eq(variables['RM'], 'no'))
      displayName: 'Deploy Function via AzureFunctionApp@1'
      inputs:
        azureSubscription: 'Service Connection Azure Functions V3'
        appType: functionAppLinux
        appName: $(webAppName)
        package: '$(Pipeline.Workspace)/**/FunctionsAppV3.zip'
        #runtimeStack: 'DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0'
        runtimeStack: 'DOCKER|mcr.microsoft.com/azure-functions/dotnet:3.0'
```
