### ISSUE TITLE
CORS settings not synchronized in AppService after update

### ISSUE THREAD

**Issue by dokuboyejo** [pulumi/pulumi-azure#564]
Some settings such as CORS do not get to be removed even after removing from configs
So, if an app service is created with a site config such as below
```
site_config:
            alwaysOn: true
            cors:
              allowedOrigins:
              - https://www.domain.com
              supportCredentials: true
            dotnetFrameworkVersion: v4.0
            ftps_state: FtpsOnly
```

Modifying the CORS setting of the app service by removing enries from config doesn't get synchronized
```
site_config:
            alwaysOn: true
            dotnetFrameworkVersion: v4.0
            ftps_state: FtpsOnly
```
